name: Pull Request Validation

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    name: Code Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      
      - name: Setup environment file
        run: cp .env.template .env
          
      - name: Install dependencies
        run: npm i
        
    #   - name: Lint check
    #     run: npm run lint
        
    #   - name: Format check
    #     run: npm run format:check
        
    #   - name: Execute tests
    #     run: npm run test


